declare namespace sap.ui.core {
    /**
    * Defines the accessible roles for ARIA support. This enumeration is used with the AccessibleRole control property. For more information, goto "Roles for Accessible Rich Internet Applications (WAI-ARIA Roles)" at the www.w3.org homepage.
    */
    export enum AccessibleRole {
        Alert = "Alert",
        AlertDialog = "AlertDialog",
        Application = "Application",
        Banner = "Banner",
        Button = "Button",
        Checkbox = "Checkbox",
        ColumnHeader = "ColumnHeader",
        Combobox = "Combobox",
        ContentInfo = "ContentInfo",
        Definition = "Definition",
        Description = "Description",
        Dialog = "Dialog",
        Directory = "Directory",
        Document = "Document",
        Grid = "Grid",
        GridCell = "GridCell",
        Group = "Group",
        Heading = "Heading",
        Img = "Img",
        Link = "Link",
        List = "List",
        Listbox = "Listbox",
        ListItem = "ListItem",
        Log = "Log",
        Main = "Main",
        Marquee = "Marquee",
        Menu = "Menu",
        Menubar = "Menubar",
        MenuItem = "MenuItem",
        MenuItemCheckbox = "MenuItemCheckbox",
        MenuItemRadio = "MenuItemRadio",
        Navigation = "Navigation",
        Note = "Note",
        Option = "Option",
        Presentation = "Presentation",
        ProgressBar = "ProgressBar",
        Radio = "Radio",
        RadioGroup = "RadioGroup",
        Region = "Region",
        Row = "Row",
        RowHeader = "RowHeader",
        Search = "Search",
        Secondary = "Secondary",
        SeeAlso = "SeeAlso",
        Separator = "Separator",
        Slider = "Slider",
        SpinButton = "SpinButton",
        Status = "Status",
        Tab = "Tab",
        Tablist = "Tablist",
        Tabpanel = "Tabpanel",
        Textbox = "Textbox",
        Timer = "Timer",
        Toolbar = "Toolbar",
        Tooltip = "Tooltip",
        Tree = "Tree",
        TreeGrid = "TreeGrid",
        TreeItem = "TreeItem",
    }
}